name: Go Tests

# Trigger workflow on every push to any branch
on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Run tests for folder matching branch name
      run: |
        BRANCH_NAME=${{ github.ref_name }}
        echo "Running tests for folder: ${BRANCH_NAME}"
        if [ -d "./${BRANCH_NAME}" ]; then
          cd ./${BRANCH_NAME}
          go test ./...
        else
          echo "No folder named ${BRANCH_NAME} found. Skipping tests."
        fi
